grounded_graph:
  kernel_type: 'radial'  # Kernel type used to construct weight matrix
  default_kernel_bandwidth: 0.22 # Default bandwidth in kernel 0.22
  bw_epsilon_factor: 2
  default_weight_to_ground: 1.e-3  # Default weight to ground 1.e-3
  default_source_radius: 0.1 #0.09  # Default source radius
  is_source_region: True
propagator:
  disable_tqdm: False
  max_iter: 1000  # Maximum number of iterations when propagating voltage
  progress_thr: 1.e-6 # Tolerance on voltage change when propagating voltage
  use_sparse: False
embedding:
  source_lvl: 3
  embedding_lvls: [5, 6] # range of embedding levels
  init_from_rougher: True
trimming:
  thr_voltage_magnitude: 1.e-3